2025-09-19 14:34:37,343 [INFO] __main__: Start
2025-09-19 14:34:37,344 [INFO] __main__: SYNC_MODE=OBJECTS
2025-09-19 14:34:37,344 [INFO] __main__: Starting object upload (parent 177537954)
2025-09-19 14:34:37,344 [DEBUG] sf_object_loader: Running CLI: C:\Program Files\sf\bin\sf.cmd sobject list --json -o Prod
2025-09-19 14:34:39,125 [INFO] sf_object_loader: LIMIT_OBJECTS enabled, restricting to first 10 objects
2025-09-19 14:34:39,126 [INFO] sf_object_loader: Describing object: AC_Corp_Form__ChangeEvent
2025-09-19 14:34:39,126 [DEBUG] sf_object_loader: Running CLI: C:\Program Files\sf\bin\sf.cmd sobject describe -s AC_Corp_Form__ChangeEvent --json -o Prod
2025-09-19 14:34:40,667 [INFO] sf_object_loader: Describing object: AC_Corp_Form__Share
2025-09-19 14:34:40,668 [DEBUG] sf_object_loader: Running CLI: C:\Program Files\sf\bin\sf.cmd sobject describe -s AC_Corp_Form__Share --json -o Prod
2025-09-19 14:34:42,240 [INFO] sf_object_loader: Describing object: AC_Corp_Form__c
2025-09-19 14:34:42,240 [DEBUG] sf_object_loader: Running CLI: C:\Program Files\sf\bin\sf.cmd sobject describe -s AC_Corp_Form__c --json -o Prod
2025-09-19 14:34:43,776 [INFO] sf_object_loader: Describing object: AIApplication
2025-09-19 14:34:43,776 [DEBUG] sf_object_loader: Running CLI: C:\Program Files\sf\bin\sf.cmd sobject describe -s AIApplication --json -o Prod
2025-09-19 14:34:45,321 [INFO] sf_object_loader: Describing object: AIApplicationConfig
2025-09-19 14:34:45,321 [DEBUG] sf_object_loader: Running CLI: C:\Program Files\sf\bin\sf.cmd sobject describe -s AIApplicationConfig --json -o Prod
2025-09-19 14:34:46,953 [INFO] sf_object_loader: Describing object: AIInsightAction
2025-09-19 14:34:46,954 [DEBUG] sf_object_loader: Running CLI: C:\Program Files\sf\bin\sf.cmd sobject describe -s AIInsightAction --json -o Prod
2025-09-19 14:34:48,705 [INFO] sf_object_loader: Describing object: AIInsightFeedback
2025-09-19 14:34:48,705 [DEBUG] sf_object_loader: Running CLI: C:\Program Files\sf\bin\sf.cmd sobject describe -s AIInsightFeedback --json -o Prod
2025-09-19 14:34:50,292 [INFO] sf_object_loader: Describing object: AIInsightReason
2025-09-19 14:34:50,293 [DEBUG] sf_object_loader: Running CLI: C:\Program Files\sf\bin\sf.cmd sobject describe -s AIInsightReason --json -o Prod
2025-09-19 14:34:51,901 [INFO] sf_object_loader: Describing object: AIInsightValue
2025-09-19 14:34:51,902 [DEBUG] sf_object_loader: Running CLI: C:\Program Files\sf\bin\sf.cmd sobject describe -s AIInsightValue --json -o Prod
2025-09-19 14:34:55,591 [INFO] sf_object_loader: Describing object: AIPredictionEvent
2025-09-19 14:34:55,591 [DEBUG] sf_object_loader: Running CLI: C:\Program Files\sf\bin\sf.cmd sobject describe -s AIPredictionEvent --json -o Prod
2025-09-19 14:34:57,138 [INFO] __main__: Uploading object: AC_Corp_Form__ChangeEvent
2025-09-19 14:34:57,140 [DEBUG] urllib3.connectionpool: Starting new HTTPS connection (1): cretemechanical.atlassian.net:443
2025-09-19 14:34:57,212 [DEBUG] urllib3.connectionpool: https://cretemechanical.atlassian.net:443 "GET /wiki/api/v2/pages?spaceId=28180482&title=AC_Corp_Form__ChangeEvent&expand=version HTTP/1.1" 200 None
2025-09-19 14:34:57,213 [ERROR] __main__: Failed to upload object AC_Corp_Form__ChangeEvent
Traceback (most recent call last):
  File "C:\Users\vm-bpa\OneDrive - Crete Mechanical\Code\UploadFlowDocumentation\main.py", line 51, in process_objects
    uploader.upload_object_doc(parent_id=parent_id, object_name=obj_name, fields=fields, meta=meta)
  File "C:\Users\vm-bpa\OneDrive - Crete Mechanical\Code\UploadFlowDocumentation\confluence_uploader.py", line 159, in upload_object_doc
    for f in sorted(fields, key=lambda x: x.get("label", "")):
  File "C:\Users\vm-bpa\OneDrive - Crete Mechanical\Code\UploadFlowDocumentation\confluence_uploader.py", line 159, in <lambda>
    for f in sorted(fields, key=lambda x: x.get("label", "")):
AttributeError: 'str' object has no attribute 'get'
2025-09-19 14:34:57,214 [INFO] __main__: Uploading object: AC_Corp_Form__Share
2025-09-19 14:34:57,215 [DEBUG] urllib3.connectionpool: Starting new HTTPS connection (1): cretemechanical.atlassian.net:443
2025-09-19 14:34:57,286 [DEBUG] urllib3.connectionpool: https://cretemechanical.atlassian.net:443 "GET /wiki/api/v2/pages?spaceId=28180482&title=AC_Corp_Form__Share&expand=version HTTP/1.1" 200 None
2025-09-19 14:34:57,287 [ERROR] __main__: Failed to upload object AC_Corp_Form__Share
Traceback (most recent call last):
  File "C:\Users\vm-bpa\OneDrive - Crete Mechanical\Code\UploadFlowDocumentation\main.py", line 51, in process_objects
    uploader.upload_object_doc(parent_id=parent_id, object_name=obj_name, fields=fields, meta=meta)
  File "C:\Users\vm-bpa\OneDrive - Crete Mechanical\Code\UploadFlowDocumentation\confluence_uploader.py", line 159, in upload_object_doc
    for f in sorted(fields, key=lambda x: x.get("label", "")):
  File "C:\Users\vm-bpa\OneDrive - Crete Mechanical\Code\UploadFlowDocumentation\confluence_uploader.py", line 159, in <lambda>
    for f in sorted(fields, key=lambda x: x.get("label", "")):
AttributeError: 'str' object has no attribute 'get'
2025-09-19 14:34:57,288 [INFO] __main__: Uploading object: AC_Corp_Form__c
2025-09-19 14:34:57,289 [DEBUG] urllib3.connectionpool: Starting new HTTPS connection (1): cretemechanical.atlassian.net:443
2025-09-19 14:34:57,337 [DEBUG] urllib3.connectionpool: https://cretemechanical.atlassian.net:443 "GET /wiki/api/v2/pages?spaceId=28180482&title=AC_Corp_Form__c&expand=version HTTP/1.1" 200 None
2025-09-19 14:34:57,337 [ERROR] __main__: Failed to upload object AC_Corp_Form__c
Traceback (most recent call last):
  File "C:\Users\vm-bpa\OneDrive - Crete Mechanical\Code\UploadFlowDocumentation\main.py", line 51, in process_objects
    uploader.upload_object_doc(parent_id=parent_id, object_name=obj_name, fields=fields, meta=meta)
  File "C:\Users\vm-bpa\OneDrive - Crete Mechanical\Code\UploadFlowDocumentation\confluence_uploader.py", line 133, in upload_object_doc
    [
TypeError: 'int' object is not iterable
2025-09-19 14:34:57,338 [INFO] __main__: Uploading object: AIApplication
2025-09-19 14:34:57,339 [DEBUG] urllib3.connectionpool: Starting new HTTPS connection (1): cretemechanical.atlassian.net:443
2025-09-19 14:34:57,405 [DEBUG] urllib3.connectionpool: https://cretemechanical.atlassian.net:443 "GET /wiki/api/v2/pages?spaceId=28180482&title=AIApplication&expand=version HTTP/1.1" 200 None
2025-09-19 14:34:57,406 [ERROR] __main__: Failed to upload object AIApplication
Traceback (most recent call last):
  File "C:\Users\vm-bpa\OneDrive - Crete Mechanical\Code\UploadFlowDocumentation\main.py", line 51, in process_objects
    uploader.upload_object_doc(parent_id=parent_id, object_name=obj_name, fields=fields, meta=meta)
  File "C:\Users\vm-bpa\OneDrive - Crete Mechanical\Code\UploadFlowDocumentation\confluence_uploader.py", line 159, in upload_object_doc
    for f in sorted(fields, key=lambda x: x.get("label", "")):
  File "C:\Users\vm-bpa\OneDrive - Crete Mechanical\Code\UploadFlowDocumentation\confluence_uploader.py", line 159, in <lambda>
    for f in sorted(fields, key=lambda x: x.get("label", "")):
AttributeError: 'str' object has no attribute 'get'
2025-09-19 14:34:57,407 [INFO] __main__: Uploading object: AIApplicationConfig
2025-09-19 14:34:57,408 [DEBUG] urllib3.connectionpool: Starting new HTTPS connection (1): cretemechanical.atlassian.net:443
2025-09-19 14:34:57,475 [DEBUG] urllib3.connectionpool: https://cretemechanical.atlassian.net:443 "GET /wiki/api/v2/pages?spaceId=28180482&title=AIApplicationConfig&expand=version HTTP/1.1" 200 None
2025-09-19 14:34:57,476 [ERROR] __main__: Failed to upload object AIApplicationConfig
Traceback (most recent call last):
  File "C:\Users\vm-bpa\OneDrive - Crete Mechanical\Code\UploadFlowDocumentation\main.py", line 51, in process_objects
    uploader.upload_object_doc(parent_id=parent_id, object_name=obj_name, fields=fields, meta=meta)
  File "C:\Users\vm-bpa\OneDrive - Crete Mechanical\Code\UploadFlowDocumentation\confluence_uploader.py", line 159, in upload_object_doc
    for f in sorted(fields, key=lambda x: x.get("label", "")):
  File "C:\Users\vm-bpa\OneDrive - Crete Mechanical\Code\UploadFlowDocumentation\confluence_uploader.py", line 159, in <lambda>
    for f in sorted(fields, key=lambda x: x.get("label", "")):
AttributeError: 'str' object has no attribute 'get'
2025-09-19 14:34:57,477 [INFO] __main__: Uploading object: AIInsightAction
2025-09-19 14:34:57,478 [DEBUG] urllib3.connectionpool: Starting new HTTPS connection (1): cretemechanical.atlassian.net:443
2025-09-19 14:34:57,545 [DEBUG] urllib3.connectionpool: https://cretemechanical.atlassian.net:443 "GET /wiki/api/v2/pages?spaceId=28180482&title=AIInsightAction&expand=version HTTP/1.1" 200 None
2025-09-19 14:34:57,546 [ERROR] __main__: Failed to upload object AIInsightAction
Traceback (most recent call last):
  File "C:\Users\vm-bpa\OneDrive - Crete Mechanical\Code\UploadFlowDocumentation\main.py", line 51, in process_objects
    uploader.upload_object_doc(parent_id=parent_id, object_name=obj_name, fields=fields, meta=meta)
  File "C:\Users\vm-bpa\OneDrive - Crete Mechanical\Code\UploadFlowDocumentation\confluence_uploader.py", line 133, in upload_object_doc
    [
TypeError: 'int' object is not iterable
2025-09-19 14:34:57,546 [INFO] __main__: Uploading object: AIInsightFeedback
2025-09-19 14:34:57,547 [DEBUG] urllib3.connectionpool: Starting new HTTPS connection (1): cretemechanical.atlassian.net:443
2025-09-19 14:34:57,592 [DEBUG] urllib3.connectionpool: https://cretemechanical.atlassian.net:443 "GET /wiki/api/v2/pages?spaceId=28180482&title=AIInsightFeedback&expand=version HTTP/1.1" 200 None
2025-09-19 14:34:57,593 [ERROR] __main__: Failed to upload object AIInsightFeedback
Traceback (most recent call last):
  File "C:\Users\vm-bpa\OneDrive - Crete Mechanical\Code\UploadFlowDocumentation\main.py", line 51, in process_objects
    uploader.upload_object_doc(parent_id=parent_id, object_name=obj_name, fields=fields, meta=meta)
  File "C:\Users\vm-bpa\OneDrive - Crete Mechanical\Code\UploadFlowDocumentation\confluence_uploader.py", line 133, in upload_object_doc
    [
TypeError: 'int' object is not iterable
2025-09-19 14:34:57,594 [INFO] __main__: Uploading object: AIInsightReason
2025-09-19 14:34:57,595 [DEBUG] urllib3.connectionpool: Starting new HTTPS connection (1): cretemechanical.atlassian.net:443
2025-09-19 14:34:57,664 [DEBUG] urllib3.connectionpool: https://cretemechanical.atlassian.net:443 "GET /wiki/api/v2/pages?spaceId=28180482&title=AIInsightReason&expand=version HTTP/1.1" 200 None
2025-09-19 14:34:57,665 [ERROR] __main__: Failed to upload object AIInsightReason
Traceback (most recent call last):
  File "C:\Users\vm-bpa\OneDrive - Crete Mechanical\Code\UploadFlowDocumentation\main.py", line 51, in process_objects
    uploader.upload_object_doc(parent_id=parent_id, object_name=obj_name, fields=fields, meta=meta)
  File "C:\Users\vm-bpa\OneDrive - Crete Mechanical\Code\UploadFlowDocumentation\confluence_uploader.py", line 133, in upload_object_doc
    [
TypeError: 'int' object is not iterable
2025-09-19 14:34:57,666 [INFO] __main__: Uploading object: AIInsightValue
2025-09-19 14:34:57,667 [DEBUG] urllib3.connectionpool: Starting new HTTPS connection (1): cretemechanical.atlassian.net:443
2025-09-19 14:34:57,761 [DEBUG] urllib3.connectionpool: https://cretemechanical.atlassian.net:443 "GET /wiki/api/v2/pages?spaceId=28180482&title=AIInsightValue&expand=version HTTP/1.1" 200 None
2025-09-19 14:34:57,762 [ERROR] __main__: Failed to upload object AIInsightValue
Traceback (most recent call last):
  File "C:\Users\vm-bpa\OneDrive - Crete Mechanical\Code\UploadFlowDocumentation\main.py", line 51, in process_objects
    uploader.upload_object_doc(parent_id=parent_id, object_name=obj_name, fields=fields, meta=meta)
  File "C:\Users\vm-bpa\OneDrive - Crete Mechanical\Code\UploadFlowDocumentation\confluence_uploader.py", line 133, in upload_object_doc
    [
TypeError: 'int' object is not iterable
2025-09-19 14:34:57,762 [INFO] __main__: Uploading object: AIPredictionEvent
2025-09-19 14:34:57,763 [DEBUG] urllib3.connectionpool: Starting new HTTPS connection (1): cretemechanical.atlassian.net:443
2025-09-19 14:34:57,809 [DEBUG] urllib3.connectionpool: https://cretemechanical.atlassian.net:443 "GET /wiki/api/v2/pages?spaceId=28180482&title=AIPredictionEvent&expand=version HTTP/1.1" 200 None
2025-09-19 14:34:57,810 [ERROR] __main__: Failed to upload object AIPredictionEvent
Traceback (most recent call last):
  File "C:\Users\vm-bpa\OneDrive - Crete Mechanical\Code\UploadFlowDocumentation\main.py", line 51, in process_objects
    uploader.upload_object_doc(parent_id=parent_id, object_name=obj_name, fields=fields, meta=meta)
  File "C:\Users\vm-bpa\OneDrive - Crete Mechanical\Code\UploadFlowDocumentation\confluence_uploader.py", line 159, in upload_object_doc
    for f in sorted(fields, key=lambda x: x.get("label", "")):
  File "C:\Users\vm-bpa\OneDrive - Crete Mechanical\Code\UploadFlowDocumentation\confluence_uploader.py", line 159, in <lambda>
    for f in sorted(fields, key=lambda x: x.get("label", "")):
AttributeError: 'str' object has no attribute 'get'
